# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Bash@3
      displayName: Switch to source directory
      inputs:
        targetType: 'inline'
        script: 'cd $(Build.SourcesDirectory)'
    - task: Bash@3
      displayName: Build Allwinner H3 kernel
      inputs:
        targetType: 'inline'
        script: 'cd $(Build.SourcesDirectory) && make kernel-h3-build'
    - task: Bash@3
      displayName: Build Allwinner H5 kernel
      inputs:
        targetType: 'inline'
        script: 'cd $(Build.SourcesDirectory) && make kernel-h5-build'
    - task: Bash@3
      displayName: Build Allwinner H6 kernel
      inputs:
        targetType: 'inline'
        script: 'cd $(Build.SourcesDirectory) && make kernel-h6-build'
    - task: Bash@3
      displayName: Build Amlogic S905 kernel
      inputs:
        targetType: 'inline'
        script: 'make kernel-s905-build'
    - task: Bash@3
      displayName: Build Amlogic S912 kernel
      inputs:
        targetType: 'inline'
        script: 'make kernel-s912-build'
    - task: Bash@3
      displayName: Build Amlogic S922X kernel
      inputs:
        targetType: 'inline'
        script: 'make kernel-s922x-build'
    - task: Bash@3
      displayName: Build Amlogic SM1 (S905x3) kernel
      inputs:
        targetType: 'inline'
        script: 'make kernel-sm1-build'
    - task: Bash@3
      displayName: Build Rockchip RK3288 kernel
      inputs:
        targetType: 'inline'
        script: 'make kernel-rk3288-build'
    - task: Bash@3
      displayName: Build Rockchip RK3326 kernel
      inputs:
        targetType: 'inline'
        script: 'make kernel-rk3326-build'
    - task: Bash@3
      displayName: Build Rockchip RK3399 kernel
      inputs:
        targetType: 'inline'
        script: 'make kernel-rk3399-build'
