# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - bash: make kernel-h3-build
      displayName: Build Allwinner H3 kernel
    - bash: make kernel-h5-build
      displayName: Build Allwinner H5 kernel
    - bash: make kernel-s905-build
      displayName: Build Amlogic S905 kernel
    - bash: make kernel-s912-build
      displayName: Build Amlogic S912 kernel
    - bash: make kernel-sm1-build
      displayName: Build Amlogic SM1 (S905x3) kernel
    - bash: make kernel-s922x-build
      displayName: Build Amlogic S922X kernel
    - bash: make kernel-rk3288-build
      displayName: Build Rockchip RK3288 kernel
    - bash: make kernel-rk3326-build
      displayName: Build Rockchip RK3326 kernel
    - bash: make kernel-rk3399-build
      displayName: Build Rockchip RK3399 kernel
