# Builds a RetroLX kernel

#
# These are the variables to edit
#

variables:
- name: version
  value: 5.15.2
- name: arch
  value: aw32

#
# This is a template, all of them SHOULD look the same
#

trigger:
  batch: true # batch changes if true; start a new build for every push if false (default)

jobs:
- job: build
  timeoutInMinutes: 360
  pool:
    vmImage: ubuntu-20.04
  container:
    image: retrolx/build-environment-ubuntu-20.10:latest
    options: --add-host invisible-mirror.net:1.1.1.1 # Blocked mirror workaround
  steps:
  - script: |
      printenv
      mkdir -p output/kernel-${{ variables.arch }}/images
      touch output/kernel-${{ variables.arch }}/images/kernel.tar.gz
      mkdir publish
      mv output/kernel-${{ variables.arch }}/images/kernel.tar.gz publish/kernel-${{ variables.arch }}-${{ variables.version }}-$(Build.BuildNumber).tar.gz
      lftp << END_SCRIPT
      open sftp://${{ REPOSITORY_HOST }}
      user ${{ REPOSITORY_USER }} ${{ REPOSITORY_PASSWORD }}
      mkdir -p www/kernel/${{ variables.arch }}/${{ variables.version }}-$(Build.BuildNumber)
      put publish/kernel-${{ variables.arch }}-${{ variables.version }}-$(Build.BuildNumber).tar.gz -o www/kernel/${{ variables.arch }}/${{ variables.version }}-$(Build.BuildNumber)/kernel-${{ variables.arch }}-${{ variables.version }}-$(Build.BuildNumber).tar.gz
      quit
      END_SCRIPT