# Builds a RetroLX kernel

#
# These are the variables to edit
#

variables:
- name: version
  value: 5.15.2
- name: arch
  value: aw32

#
# This is a template, all of them SHOULD look the same
#

trigger:
  batch: true # batch changes if true; start a new build for every push if false (default)

jobs:
- job: build
  timeoutInMinutes: 360
  pool:
    vmImage: ubuntu-20.04
  container:
    image: retrolx/build-environment-ubuntu-20.10:latest
    options: --add-host invisible-mirror.net:1.1.1.1 # Blocked mirror workaround
  steps:
  - script: printenv
    git submodule init && git submodule update
    make kernel-${{ variables.arch }}-build
    mkdir publish
    mv output/kernel-${{ variables.arch }}/images/kernel.tar.gz publish/kernel-${{ variables.arch }}-${{ variables.version }}-$(Build.BuildNumber).tar.gz