# Builds a RetroLX kernel Test

trigger:
- ci-wip

pool:
  vmImage: ubuntu-20.04

container:
  image: retrolx/build-environment-ubuntu-20.10:latest
  options: --add-host invisible-mirror.net:1.1.1.1 # Blocked mirror workaround

resources:
- repo: self

steps:
- script: printenv
- script: git submodule init
- script: git submodule update
- script: make kernel-aw32-build
# - script: mkdir -p output/kernel-aw32/images/
# - script: touch output/kernel-aw32/images/kernel.tar.gz
- script: mkdir publish
- script: mv output/kernel-aw32/images/kernel.tar.gz publish/kernel-aw32-5.15.2.tar.gz
- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: 'publish'
    vstsFeedPublish: 'RetroLX kernels/Kernels'
    vstsFeedPackagePublish: 'kernel-aw32'
    versionOption: custom
    versionPublish: '5.15.2-2021.11.17'
    packagePublishDescription: 'Kernel for aw32 with version 5.15.2'
